name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 New Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🛠️ Maintenance
    labels:
      - chore
      - refactor
  - title: 📚 Documentation
    labels:
      - documentation
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## 🚀 Yeni Sürüm: $RELEASE_TITLE
  $CHANGES
